version: '3.6'
services:
 service:
   build:
     context: .
     target: service
   ports:
     - "8080:8080"
   command: uvicorn app.main:app --host 0.0.0.0 --port 8080

  db:
    image: postgres:14.3-alpine
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"