# coding: utf-8

"""
    Swagger Petstore - OpenAPI 3.0

    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)

    The version of the OpenAPI document: 1.0.11
    Contact: apiteam@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from app.apis.diary_api import router as DiaryApiRouter
from app.apis.family_api import router as FamilyApiRouter
from app.apis.shopping_list_api import router as ShoppingListApiRouter
from app.apis.task_api import router as TaskApiRouter
from app.apis.wishlist_api import router as WishlistApiRouter
from app.data.database import engine

from app.data import models

models.Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="All for Moms",
    description="This is MVP of 'All for Moms' web application",
    version="0.1.0",
)

app.include_router(DiaryApiRouter)
app.include_router(FamilyApiRouter)
app.include_router(ShoppingListApiRouter)
app.include_router(TaskApiRouter)
app.include_router(WishlistApiRouter)
